### ISSUE TITLE
TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix

### ISSUE THREAD

**Issue by ayavilevich** [kennu/cwtail#9]
Installed with ``npm install -g cwtail``

When running ``cwtail -l`` I get:

```
TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix

    See http://goo.gl/MqrFmX

    at checkValid (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promisify.js:54:27)
    at promisifiableMethods (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promisify.js:77:5)
    at promisifyAll (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promisify.js:241:9)
    at Function.Promise.promisifyAll (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promisify.js:311:12)
    at C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\index.js:192:13
    at tryCatcher (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\promise.js:606:10)
    at _drainQueueStep (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\arik\AppData\Roaming\npm\node_modules\cwtail\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Looks like some kind of a (version) incompatibility with the bluebird module. Any idea how to resolve?

**Comment by ayavilevich** [comment]
Seems to be related to https://github.com/aws/aws-sdk-js/issues/2229

**Comment by kennu** [comment]
It's been quite a while since making this package but the dependencies are supposed to be somewhat locked.. I wonder which one has been updated to be incompatible.

**Comment by huksley** [comment]
@kennu I believe they are not since you don`t have a package-lock.json file in your repository? Getting the same error.

**Comment by ankon** [comment]
> I wonder which one has been updated to be incompatible.

Seems the aws-sdk did an incompatible change in one of their updates (see the linked issue). But, looking at the code there's no reason to bother with working around that, as the [aws-sdk also supports promises](https://aws.amazon.com/blogs/developer/support-for-promises-in-the-sdk/) since a while natively.

**Comment by romanovzky** [comment]
Is there any news on this?

**Comment by kennu** [comment]
I have unfortunately not been very active with this, but it seems AWS CLI v2 is getting official support for similar purpose: https://twitter.com/esh/status/1067148930977161216
